---
name: Net-Transmission
version: 0.01_03
author:
  - 'Zahatski Aliaksandr, E<lt>zag@cpan.orgE<gt>'
abstract: Perl interface to Transmission
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Collection: 0.43
configure_requires:
  Module::Build: 0.35
provides:
  Net::Transmission:
    file: lib/Net/Transmission.pm
    version: 0.01_03
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
